apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: moalog
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: otlp-grpc
      name: otlp-grpc
    - port: 4318
      targetPort: otlp-http
      name: otlp-http
    - port: 8889
      targetPort: prometheus
      name: prometheus
  selector:
    app: otel-collector
