apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - cert-manager.yaml
  - patches/prod-hpa.yaml
  - patches/prod-hpa-rate-limiter.yaml
  - patches/prod-hpa-fluxpay.yaml

commonLabels:
  environment: prod

patchesStrategicMerge:
  - patches/prod-resources.yaml
  - patches/prod-resources-rate-limiter.yaml
  - patches/prod-resources-fluxpay.yaml
