apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: moalog
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - port: 16686
      targetPort: ui
      name: ui
    - port: 4317
      targetPort: otlp-grpc
      name: otlp-grpc
    - port: 4318
      targetPort: otlp-http
      name: otlp-http
  selector:
    app: jaeger
