apiVersion: v1
kind: Service
metadata:
  name: fluxpay-postgres
  namespace: moalog
  labels:
    app: fluxpay-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
  selector:
    app: fluxpay-postgres
