apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: moalog
data:
  01-create-exporter-user.sql: |
    CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY 'exporter_password';
    GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
    FLUSH PRIVILEGES;
