apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: moalog
spec:
  type: ClusterIP
  ports:
    - port: 9121
      targetPort: metrics
      name: metrics
  selector:
    app: redis-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: moalog
spec:
  type: ClusterIP
  ports:
    - port: 9104
      targetPort: metrics
      name: metrics
  selector:
    app: mysqld-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: rjmx-exporter-rate-limiter
  namespace: moalog
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: metrics
      name: metrics
  selector:
    app: rjmx-exporter-rate-limiter
---
apiVersion: v1
kind: Service
metadata:
  name: rjmx-exporter-fluxpay
  namespace: moalog
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: metrics
      name: metrics
  selector:
    app: rjmx-exporter-fluxpay
